// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package otel

import (
	"context"
	"github.com/angelokurtis/go-starter-otel/internal/env"
	"github.com/angelokurtis/go-starter-otel/internal/trace"
	"go.opentelemetry.io/otel/sdk/resource"
)

// Injectors from wire_inj.go:

// Init is an initializer for an OpenTelemetry provider that offers a high level of configurability
func Init(ctx context.Context) (Provider, error) {
	resourceResource := resource.Environment()
	oTel, err := env.LookupOTel()
	if err != nil {
		return nil, err
	}
	config := env.ToTrace(oTel)
	sampler, err := trace.NewSampler(ctx, config)
	if err != nil {
		return nil, err
	}
	client, err := trace.NewTraceClient(config)
	if err != nil {
		return nil, err
	}
	v, err := trace.NewSpanExporters(ctx, config, client)
	if err != nil {
		return nil, err
	}
	tracerProvider := trace.NewTracerProvider(resourceResource, sampler, v, config)
	otelProvider := &provider{
		tracer: tracerProvider,
	}
	return otelProvider, nil
}
